language: erlang
otp_release:
  - R16B
before_install:
  - wget https://github.com/elixir-lang/elixir/archive/v0.10.3.tar.gz
  - tar -xf v0.10.3.tar.gz
  - cd elixir-0.10.3
  - make
  - export PATH="$PATH:/home/travis/build/benlangfeld/exhearsion/elixir-0.10.3/bin"
  - cd ..
install:
  - mix deps.get
script: mix test
